package modules

import (
	"context"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/ricelines/matrix-mcp/internal/catalog"
	matrixclient "github.com/ricelines/matrix-mcp/internal/matrix"
	"github.com/ricelines/matrix-mcp/internal/scopes"
)

type registerAvailableInput struct {
	Username string `json:"username" jsonschema:"Matrix localpart to check for registration availability"`
}

type registerAvailableOutput struct {
	BaseResult
	Available bool `json:"available" jsonschema:"Whether the username is available for registration"`
}

type createUserInput struct {
	Username                 string `json:"username" jsonschema:"New Matrix username localpart"`
	Password                 string `json:"password,omitempty" jsonschema:"Optional password. When omitted, the server generates one and returns it."`
	InitialDeviceDisplayName string `json:"initial_device_display_name,omitempty" jsonschema:"Optional initial device display name for the created account"`
	InhibitLogin             bool   `json:"inhibit_login,omitempty" jsonschema:"When true, request account creation without an initial access token"`
}

type createUserOutput struct {
	BaseResult
	UserID            string `json:"user_id" jsonschema:"Newly created Matrix user ID"`
	DeviceID          string `json:"device_id,omitempty" jsonschema:"Initial device ID when login was not inhibited"`
	AccessToken       string `json:"access_token,omitempty" jsonschema:"Initial access token when login was not inhibited"`
	Password          string `json:"password,omitempty" jsonschema:"Generated password when the request omitted one"`
	PasswordGenerated bool   `json:"password_generated" jsonschema:"Whether the password was generated by the server"`
}

type searchUsersInput struct {
	Query string `json:"query" jsonschema:"Search term for Matrix user directory lookup"`
	Limit int    `json:"limit,omitempty" jsonschema:"Maximum number of results to return"`
}

type searchUsersOutput struct {
	BaseResult
	Results []matrixclient.SearchUser `json:"results" jsonschema:"Matching Matrix users"`
	Limited bool                      `json:"limited" jsonschema:"Whether the homeserver limited the result set"`
}

type userProfileInput struct {
	UserID string `json:"user_id" jsonschema:"Matrix user ID to fetch"`
}

type userProfileOutput struct {
	BaseResult
	Profile matrixclient.UserProfile `json:"profile"`
}

func RegisterUsers(r *catalog.Registrar, deps Dependencies, active scopes.Set) {
	r.AddModule("users", "User lookup, registration availability, and account creation.")

	if active.Allows(scopes.ScopeUsersRead) {
		catalog.AddTool(r, "users", scopes.ScopeUsersRead, &mcp.Tool{
			Name:        "matrix.v1.users.register_available",
			Description: "Check whether a Matrix username is available for registration.",
		}, func(ctx context.Context, req *mcp.CallToolRequest, input registerAvailableInput) (*mcp.CallToolResult, registerAvailableOutput, error) {
			if err := requireNonEmpty("username", input.Username); err != nil {
				return nil, registerAvailableOutput{}, err
			}
			available, err := deps.Matrix.RegisterAvailable(ctx, input.Username)
			if err != nil {
				return nil, registerAvailableOutput{}, err
			}
			return nil, registerAvailableOutput{BaseResult: deps.baseResult(), Available: available}, nil
		})

		catalog.AddTool(r, "users", scopes.ScopeUsersRead, &mcp.Tool{
			Name:        "matrix.v1.users.search",
			Description: "Search the Matrix user directory by ID or display name.",
		}, func(ctx context.Context, req *mcp.CallToolRequest, input searchUsersInput) (*mcp.CallToolResult, searchUsersOutput, error) {
			if err := requireNonEmpty("query", input.Query); err != nil {
				return nil, searchUsersOutput{}, err
			}
			results, limited, err := deps.Matrix.SearchUsers(ctx, input.Query, input.Limit)
			if err != nil {
				return nil, searchUsersOutput{}, err
			}
			output := searchUsersOutput{BaseResult: deps.baseResult(), Limited: limited, Results: []matrixclient.SearchUser{}}
			output.Results = append(output.Results, results...)
			return nil, output, nil
		})

		catalog.AddTool(r, "users", scopes.ScopeUsersRead, &mcp.Tool{
			Name:        "matrix.v1.users.profile.get",
			Description: "Fetch the profile for a specific Matrix user ID.",
		}, func(ctx context.Context, req *mcp.CallToolRequest, input userProfileInput) (*mcp.CallToolResult, userProfileOutput, error) {
			if err := requireNonEmpty("user_id", input.UserID); err != nil {
				return nil, userProfileOutput{}, err
			}
			profile, err := deps.Matrix.GetProfile(ctx, input.UserID)
			if err != nil {
				return nil, userProfileOutput{}, err
			}
			return nil, userProfileOutput{BaseResult: deps.baseResult(), Profile: profile}, nil
		})
	}

	if active.Allows(scopes.ScopeUsersCreate) {
		catalog.AddTool(r, "users", scopes.ScopeUsersCreate, &mcp.Tool{
			Name:        "matrix.v1.users.create",
			Description: "Create a new Matrix user using the homeserver registration API. If the homeserver requires a registration token, configure it when starting matrix-mcp.",
		}, func(ctx context.Context, req *mcp.CallToolRequest, input createUserInput) (*mcp.CallToolResult, createUserOutput, error) {
			if err := requireNonEmpty("username", input.Username); err != nil {
				return nil, createUserOutput{}, err
			}
			if strings.Contains(input.Username, "@") {
				return nil, createUserOutput{}, fmt.Errorf("username must be a localpart, not a full user ID")
			}
			created, err := deps.Matrix.CreateUser(ctx, matrixclient.CreateUserRequest{
				Username:                 input.Username,
				Password:                 input.Password,
				InitialDeviceDisplayName: input.InitialDeviceDisplayName,
				InhibitLogin:             input.InhibitLogin,
			})
			if err != nil {
				return nil, createUserOutput{}, err
			}
			return nil, createUserOutput{
				BaseResult:        deps.baseResult(),
				UserID:            created.UserID,
				DeviceID:          created.DeviceID,
				AccessToken:       created.AccessToken,
				Password:          created.Password,
				PasswordGenerated: created.PasswordGenerated,
			}, nil
		})
	}
}
